# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form\ChatApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageBox(object):
    def setupUi(self, MessageBox):
        MessageBox.setObjectName("MessageBox")
        MessageBox.resize(404, 561)
        self.verticalLayoutWidget = QtWidgets.QWidget(MessageBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 10, 296, 541))
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(MessageBox)
        self.listWidget.setGeometry(QtCore.QRect(5, 11, 91, 411))
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_3 = QtWidgets.QPushButton(MessageBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 430, 81, 41))
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(MessageBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 470, 81, 41))
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(MessageBox)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 510, 81, 41))
        font = QtGui.QFont()
        font.setFamily("IRANYekan")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(MessageBox)
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        _translate = QtCore.QCoreApplication.translate
        MessageBox.setWindowTitle(_translate("MessageBox", "Chat App"))
        self.pushButton.setText(_translate("MessageBox", "send"))
        self.pushButton_2.setText(_translate("MessageBox", "Files"))
        self.pushButton_3.setText(_translate("MessageBox", "Add "))
        self.pushButton_4.setText(_translate("MessageBox", "Group"))
        self.pushButton_5.setText(_translate("MessageBox", "Channel"))
